// Comprehensive realistic mock database for HirebridgeHR

export const initialOrganizations = [
  {
    id: 'org-1',
    name: 'Apex Global Tech',
    slug: 'apex-global-tech',
    type: 'COMPANY',
    industry: 'Enterprise Software & Cloud',
    size: '250-500',
    website: 'https://apextech.example.com',
    country: 'United States',
    city: 'San Francisco, CA',
    timeZone: 'America/Los_Angeles',
    status: 'ACTIVE',
    createdAt: '2025-01-15T08:00:00Z',
    activeJobsCount: 8,
    totalHires: 34,
  },
  {
    id: 'org-2',
    name: 'Quantum Staffing Solutions',
    slug: 'quantum-staffing',
    type: 'STAFFING',
    industry: 'IT & Financial Services Staffing',
    size: '50-100',
    website: 'https://quantumstaffing.example.com',
    country: 'United Kingdom',
    city: 'London',
    timeZone: 'Europe/London',
    status: 'ACTIVE',
    createdAt: '2025-02-01T10:30:00Z',
    activeJobsCount: 14,
    totalHires: 62,
  },
  {
    id: 'org-3',
    name: 'TalentPulse Recruitment Agency',
    slug: 'talentpulse-agency',
    type: 'AGENCY',
    industry: 'Executive & Tech Recruitment',
    size: '20-50',
    website: 'https://talentpulse.example.com',
    country: 'India',
    city: 'Bengaluru',
    timeZone: 'Asia/Kolkata',
    status: 'ACTIVE',
    createdAt: '2025-02-20T11:15:00Z',
    activeJobsCount: 19,
    totalHires: 88,
  },
];

export const mockUsers = [
  {
    id: 'usr-1',
    name: 'Sarah Connor',
    email: 'sarah.connor@apextech.com',
    role: 'OWNER',
    organizationId: 'org-1',
    organizationName: 'Apex Global Tech',
    jobTitle: 'Head of Talent Acquisition',
    phone: '+1 (415) 890-1234',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'usr-2',
    name: 'Marcus Vance',
    email: 'marcus.vance@apextech.com',
    role: 'ADMIN',
    organizationId: 'org-1',
    organizationName: 'Apex Global Tech',
    jobTitle: 'Senior HR Business Partner',
    phone: '+1 (415) 765-4321',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'usr-3',
    name: 'Elena Rostova',
    email: 'elena.rostova@apextech.com',
    role: 'RECRUITER',
    organizationId: 'org-1',
    organizationName: 'Apex Global Tech',
    jobTitle: 'Lead Technical Recruiter',
    phone: '+1 (415) 321-9876',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'usr-4',
    name: 'David Chen',
    email: 'david.chen@apextech.com',
    role: 'HIRING_MANAGER',
    organizationId: 'org-1',
    organizationName: 'Apex Global Tech',
    jobTitle: 'VP of Engineering',
    phone: '+1 (415) 654-7890',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'usr-5',
    name: 'Alex Mercer',
    email: 'alex.mercer@hirebridge.internal',
    role: 'SUPER_ADMIN',
    organizationId: 'sys-admin',
    organizationName: 'HirebridgeHR System Operations',
    jobTitle: 'Platform Master Admin',
    phone: '+1 (800) 555-0199',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
  },
  {
    id: 'usr-cand-1',
    name: 'Alex Rivera',
    firstName: 'Alex',
    lastName: 'Rivera',
    email: 'alex.candidate@example.com',
    role: 'CANDIDATE',
    organizationId: null,
    organizationName: 'Candidate Portal',
    jobTitle: 'Senior Full Stack & Mobile Engineer',
    phone: '+1 (555) 234-5678',
    location: 'San Francisco, CA',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    createdAt: '2025-02-10T12:00:00Z',
  },
];

export const initialJobs = [
  {
    id: 'job-101',
    slug: 'senior-full-stack-engineer',
    title: 'Senior Full Stack Engineer',
    client: 'FinTech Cloud Division',
    department: 'Engineering',
    location: 'San Francisco, CA',
    workplaceType: 'Hybrid',
    employmentType: 'Full-time',
    experienceMin: 5,
    experienceMax: 8,
    experienceLevel: 'Senior',
    salaryMin: 140000,
    salaryMax: 185000,
    currency: 'USD',
    skills: ['React.js', 'Node.js', 'TypeScript', 'PostgreSQL', 'AWS', 'Docker'],
    description: `### About the Position
Apex Global Tech is seeking an experienced Senior Full Stack Engineer to architect and expand our distributed real-time ledger platform. You will spearhead our client-facing dashboards and scalable microservices.

### Key Responsibilities
- Architect high-throughput RESTful and GraphQL APIs with Node.js and PostgreSQL.
- Construct responsive, accessible, liquid-glass web interfaces in React.js.
- Champion code reviews, continuous integration, and observability best practices.
- Collaborate closely with Product and UX teams on enterprise requirements.

### Qualifications
- 5+ years of production experience in React, TypeScript, and modern backend stacks.
- Solid background in relational data modeling and Redis caching layers.
- Hands-on familiarity with Kubernetes and cloud deployment pipelines.`,
    status: 'PUBLISHED',
    recruiterId: 'usr-3',
    recruiterName: 'Elena Rostova',
    contactPerson: 'Elena Rostova (elena.rostova@apextech.com)',
    candidateEmail: 'careers@apextech.example.com',
    isPublic: true,
    isResumeRequired: true,
    deadline: '2026-10-30',
    applicationsCount: 28,
    createdAt: '2026-03-01T10:00:00Z',
    publishedAt: '2026-03-02T14:30:00Z',
    distribution: [
      { platform: 'MANUAL', status: 'PUBLISHED', publishedAt: '2026-03-02T14:30:00Z', externalJobId: 'HB-PUB-99182' },
      { platform: 'LINKEDIN', status: 'READY', publishedAt: null, externalJobId: null },
      { platform: 'INDEED', status: 'READY', publishedAt: null, externalJobId: null },
      { platform: 'GOOGLE_JOBS', status: 'READY', publishedAt: null, externalJobId: null },
    ],
  },
  {
    id: 'job-102',
    slug: 'lead-devops-cloud-architect',
    title: 'Lead DevOps & Cloud Architect',
    client: 'Infrastructure Core',
    department: 'DevOps & SRE',
    location: 'Remote (US/Canada)',
    workplaceType: 'Remote',
    employmentType: 'Full-time',
    experienceMin: 7,
    experienceMax: 12,
    experienceLevel: 'Lead',
    salaryMin: 165000,
    salaryMax: 210000,
    currency: 'USD',
    skills: ['Kubernetes', 'Terraform', 'AWS', 'CI/CD', 'Prometheus', 'Python'],
    description: `### Overview
We are looking for a visionary Lead DevOps & Cloud Architect to lead infrastructure reliability, automated scaling, and security compliance across multiple regions.

### Responsibilities
- Manage multi-cluster AWS EKS infrastructure with Terraform IaC.
- Implement zero-trust security postures and SOC2 automated compliance policies.
- Mentor junior SREs and establish proactive incident management protocols.`,
    status: 'PENDING_ADMIN_PUBLICATION',
    recruiterId: 'usr-3',
    recruiterName: 'Elena Rostova',
    contactPerson: 'Elena Rostova',
    candidateEmail: 'careers@apextech.example.com',
    isPublic: true,
    isResumeRequired: true,
    deadline: '2026-11-15',
    applicationsCount: 14,
    createdAt: '2026-03-10T09:15:00Z',
    publishedAt: null,
    distribution: [
      { platform: 'MANUAL', status: 'PENDING', requestedAt: '2026-03-10T09:30:00Z', externalJobId: null },
    ],
  },
  {
    id: 'job-103',
    slug: 'senior-product-designer',
    title: 'Senior Product Designer (Design Systems)',
    client: 'UX & Platform Experience',
    department: 'Design',
    location: 'New York, NY',
    workplaceType: 'On-site',
    employmentType: 'Full-time',
    experienceMin: 4,
    experienceMax: 7,
    experienceLevel: 'Mid-Senior',
    salaryMin: 125000,
    salaryMax: 160000,
    currency: 'USD',
    skills: ['Figma', 'Design Systems', 'Prototyping', 'Accessibility (WCAG)', 'User Research'],
    description: `Elevate our multi-tenant SaaS interfaces through refined typography, clean spatial hierarchy, and liquid glass interactions. Work directly with frontend engineering to produce production design tokens.`,
    status: 'PUBLISHED',
    recruiterId: 'usr-1',
    recruiterName: 'Sarah Connor',
    contactPerson: 'Sarah Connor',
    candidateEmail: 'design-careers@apextech.example.com',
    isPublic: true,
    isResumeRequired: true,
    deadline: '2026-11-01',
    applicationsCount: 39,
    createdAt: '2026-02-18T14:20:00Z',
    publishedAt: '2026-02-19T11:00:00Z',
    distribution: [
      { platform: 'MANUAL', status: 'PUBLISHED', publishedAt: '2026-02-19T11:00:00Z', externalJobId: 'HB-PUB-88210' },
    ],
  },
  {
    id: 'job-104',
    slug: 'ai-machine-learning-engineer',
    title: 'Senior AI / ML Research Engineer',
    client: 'Data & Cognitive Intelligence',
    department: 'Artificial Intelligence',
    location: 'San Francisco, CA',
    workplaceType: 'Hybrid',
    employmentType: 'Full-time',
    experienceMin: 5,
    experienceMax: 9,
    experienceLevel: 'Senior',
    salaryMin: 175000,
    salaryMax: 235000,
    currency: 'USD',
    skills: ['Python', 'PyTorch', 'FastAPI', 'Vector Databases', 'Hugging Face', 'Transformers'],
    description: `Develop state-of-the-art semantic search, resume intelligence graphs, and algorithmic candidate ranking models with low-latency inference endpoints.`,
    status: 'DRAFT',
    recruiterId: 'usr-3',
    recruiterName: 'Elena Rostova',
    contactPerson: 'Elena Rostova',
    candidateEmail: 'careers@apextech.example.com',
    isPublic: false,
    isResumeRequired: true,
    deadline: '2026-12-01',
    applicationsCount: 0,
    createdAt: '2026-03-15T16:45:00Z',
    publishedAt: null,
    distribution: [],
  },
  {
    id: 'job-105',
    slug: 'customer-success-lead-emea',
    title: 'Customer Success & Onboarding Lead',
    client: 'Enterprise Growth',
    department: 'Customer Operations',
    location: 'London, UK',
    workplaceType: 'Hybrid',
    employmentType: 'Full-time',
    experienceMin: 4,
    experienceMax: 8,
    experienceLevel: 'Mid-Senior',
    salaryMin: 75000,
    salaryMax: 95000,
    currency: 'GBP',
    skills: ['SaaS Onboarding', 'Enterprise Retention', 'Zendesk', 'HubSpot', 'Executive Presentation'],
    description: `Drive high-touch enterprise onboarding and account health retention for Tier-1 corporate recruitment agencies.`,
    status: 'CLOSED',
    recruiterId: 'usr-2',
    recruiterName: 'Marcus Vance',
    contactPerson: 'Marcus Vance',
    candidateEmail: 'careers@apextech.example.com',
    isPublic: false,
    isResumeRequired: true,
    deadline: '2026-03-01',
    applicationsCount: 42,
    createdAt: '2026-01-10T11:00:00Z',
    publishedAt: '2026-01-12T09:00:00Z',
    distribution: [],
  },
];

export const initialCandidates = [
  {
    id: 'cand-1',
    name: 'Alexander Wright',
    email: 'alex.wright@techinnovate.dev',
    phone: '+1 (555) 234-5678',
    currentTitle: 'Senior Backend Engineer',
    currentCompany: 'FinStream Systems',
    location: 'Seattle, WA',
    experienceYears: 6.5,
    skills: ['Node.js', 'PostgreSQL', 'TypeScript', 'Docker', 'AWS', 'Redis'],
    source: 'LinkedIn',
    status: 'INTERVIEW',
    assignedRecruiterId: 'usr-3',
    assignedRecruiterName: 'Elena Rostova',
    tags: ['Senior', 'Strong Communicator', 'Immediate Joiner'],
    resume: {
      fileName: 'Alexander_Wright_Resume_2026.pdf',
      fileSize: '412 KB',
      uploadedAt: '2026-03-03T11:24:00Z',
    },
    notes: [
      { id: 'note-1', author: 'Elena Rostova', content: 'Screened candidate over phone. Outstanding depth in distributed database concurrency. Recommending technical round.', createdAt: '2026-03-04T15:00:00Z' },
    ],
    timeline: [
      { id: 'time-1', title: 'Applied for Senior Full Stack Engineer', date: '2026-03-03T11:24:00Z', type: 'application' },
      { id: 'time-2', title: 'Screening Completed by Elena Rostova', date: '2026-03-04T15:00:00Z', type: 'status_change' },
      { id: 'time-3', title: 'Technical Interview Scheduled with David Chen', date: '2026-03-06T10:00:00Z', type: 'interview' },
    ],
  },
  {
    id: 'cand-2',
    name: 'Priya Sharma',
    email: 'priya.sharma@cloudstack.io',
    phone: '+1 (555) 876-5432',
    currentTitle: 'Principal Cloud Engineer',
    currentCompany: 'TerraScale Networks',
    location: 'Austin, TX',
    experienceYears: 8.0,
    skills: ['Kubernetes', 'Terraform', 'AWS', 'Go', 'Prometheus', 'CI/CD'],
    source: 'Referral',
    status: 'SHORTLISTED',
    assignedRecruiterId: 'usr-3',
    assignedRecruiterName: 'Elena Rostova',
    tags: ['Principal Level', 'Kubernetes Expert', 'High Priority'],
    resume: {
      fileName: 'Priya_Sharma_Principal_DevOps.pdf',
      fileSize: '328 KB',
      uploadedAt: '2026-03-11T14:10:00Z',
    },
    notes: [
      { id: 'note-2', author: 'David Chen', content: 'Internal referral from our former DevOps lead. Resume looks exceptional.', createdAt: '2026-03-12T09:30:00Z' },
    ],
    timeline: [
      { id: 'time-4', title: 'Applied for Lead DevOps & Cloud Architect', date: '2026-03-11T14:10:00Z', type: 'application' },
      { id: 'time-5', title: 'Shortlisted by David Chen', date: '2026-03-12T09:30:00Z', type: 'status_change' },
    ],
  },
  {
    id: 'cand-3',
    name: 'Julian Vance',
    email: 'julian.vance@designcraft.studio',
    phone: '+1 (555) 345-9876',
    currentTitle: 'Lead Design Systems Specialist',
    currentCompany: 'Forma Interactive',
    location: 'Brooklyn, NY',
    experienceYears: 5.5,
    skills: ['Figma', 'Design Systems', 'WCAG', 'Typography', 'Framer', 'Prototyping'],
    source: 'Career Page',
    status: 'OFFER',
    assignedRecruiterId: 'usr-1',
    assignedRecruiterName: 'Sarah Connor',
    tags: ['Top Tier Design', 'Design Token Pioneer'],
    resume: {
      fileName: 'Julian_Vance_Design_Portfolio_Resume.pdf',
      fileSize: '1.2 MB',
      uploadedAt: '2026-02-22T08:45:00Z',
    },
    notes: [
      { id: 'note-3', author: 'Sarah Connor', content: 'Completed final design presentation round. Consensus across executives is a strong YES. Offer letter generated.', createdAt: '2026-03-08T16:00:00Z' },
    ],
    timeline: [
      { id: 'time-6', title: 'Applied for Senior Product Designer', date: '2026-02-22T08:45:00Z', type: 'application' },
      { id: 'time-7', title: 'Shortlisted for Portfolio Review', date: '2026-02-24T10:00:00Z', type: 'status_change' },
      { id: 'time-8', title: 'Panel Interview Completed', date: '2026-03-05T14:00:00Z', type: 'interview' },
      { id: 'time-9', title: 'Offer Extended ($155,000 + Equity)', date: '2026-03-08T16:00:00Z', type: 'offer' },
    ],
  },
  {
    id: 'cand-4',
    name: 'Maya Lin',
    email: 'maya.lin@cognitiveintelligence.ai',
    phone: '+1 (555) 432-1098',
    currentTitle: 'Research Scientist',
    currentCompany: 'NeuralEdge Labs',
    location: 'San Jose, CA',
    experienceYears: 7.0,
    skills: ['Python', 'PyTorch', 'Vector Search', 'LLMs', 'C++', 'FastAPI'],
    source: 'Direct Sourcing',
    status: 'NEW',
    assignedRecruiterId: 'usr-3',
    assignedRecruiterName: 'Elena Rostova',
    tags: ['PhD', 'Published Researcher', 'Semantic Search'],
    resume: {
      fileName: 'Maya_Lin_CV_Research.pdf',
      fileSize: '540 KB',
      uploadedAt: '2026-03-16T12:00:00Z',
    },
    notes: [],
    timeline: [
      { id: 'time-10', title: 'Sourced candidate profile added to pipeline', date: '2026-03-16T12:00:00Z', type: 'application' },
    ],
  },
  {
    id: 'cand-5',
    name: 'Rohan Mehta',
    email: 'rohan.mehta@fintechstack.org',
    phone: '+1 (555) 789-0123',
    currentTitle: 'Full Stack Web Developer',
    currentCompany: 'Nexus Payments',
    location: 'San Francisco, CA',
    experienceYears: 4.5,
    skills: ['React.js', 'Node.js', 'PostgreSQL', 'Tailwind CSS', 'Docker'],
    source: 'LinkedIn',
    status: 'SCREENING',
    assignedRecruiterId: 'usr-3',
    assignedRecruiterName: 'Elena Rostova',
    tags: ['React Pro', 'Available in 2 Weeks'],
    resume: {
      fileName: 'Rohan_Mehta_Resume.pdf',
      fileSize: '310 KB',
      uploadedAt: '2026-03-14T09:12:00Z',
    },
    notes: [
      { id: 'note-4', author: 'Elena Rostova', content: 'Phone screen scheduled for tomorrow morning.', createdAt: '2026-03-15T11:00:00Z' },
    ],
    timeline: [
      { id: 'time-11', title: 'Applied for Senior Full Stack Engineer', date: '2026-03-14T09:12:00Z', type: 'application' },
      { id: 'time-12', title: 'Moved to Initial Screening Stage', date: '2026-03-15T11:00:00Z', type: 'status_change' },
    ],
  },
  {
    id: 'cand-6',
    name: 'Chloe Tremblay',
    email: 'chloe.tremblay@enterpriseops.co',
    phone: '+1 (555) 678-9012',
    currentTitle: 'Customer Success Manager',
    currentCompany: 'Acme SaaS EMEA',
    location: 'Montreal, Canada',
    experienceYears: 5.0,
    skills: ['SaaS Onboarding', 'Zendesk', 'Client Retention', 'Bilingual English/French'],
    source: 'Referral',
    status: 'HIRED',
    assignedRecruiterId: 'usr-2',
    assignedRecruiterName: 'Marcus Vance',
    tags: ['Bilingual', 'Hired', 'Top Performer'],
    resume: {
      fileName: 'Chloe_Tremblay_CS_Resume.pdf',
      fileSize: '295 KB',
      uploadedAt: '2026-01-20T10:00:00Z',
    },
    notes: [
      { id: 'note-5', author: 'Marcus Vance', content: 'Offer accepted! Joining date set to April 1st.', createdAt: '2026-02-15T14:30:00Z' },
    ],
    timeline: [
      { id: 'time-13', title: 'Candidate Accepted Offer & Hired', date: '2026-02-15T14:30:00Z', type: 'hire' },
    ],
  },
];

export const initialApplications = [
  {
    id: 'app-501',
    candidateId: 'cand-1',
    candidateName: 'Alexander Wright',
    candidateEmail: 'alex.wright@techinnovate.dev',
    jobId: 'job-101',
    jobTitle: 'Senior Full Stack Engineer',
    stage: 'INTERVIEW',
    appliedDate: '2026-03-03T11:24:00Z',
    source: 'LinkedIn',
    recruiterId: 'usr-3',
    recruiterName: 'Elena Rostova',
    rating: 4.8,
  },
  {
    id: 'app-502',
    candidateId: 'cand-2',
    candidateName: 'Priya Sharma',
    candidateEmail: 'priya.sharma@cloudstack.io',
    jobId: 'job-102',
    jobTitle: 'Lead DevOps & Cloud Architect',
    stage: 'SHORTLISTED',
    appliedDate: '2026-03-11T14:10:00Z',
    source: 'Referral',
    recruiterId: 'usr-3',
    recruiterName: 'Elena Rostova',
    rating: 4.9,
  },
  {
    id: 'app-503',
    candidateId: 'cand-3',
    candidateName: 'Julian Vance',
    candidateEmail: 'julian.vance@designcraft.studio',
    jobId: 'job-103',
    jobTitle: 'Senior Product Designer (Design Systems)',
    stage: 'OFFER',
    appliedDate: '2026-02-22T08:45:00Z',
    source: 'Career Page',
    recruiterId: 'usr-1',
    recruiterName: 'Sarah Connor',
    rating: 5.0,
  },
  {
    id: 'app-504',
    candidateId: 'cand-4',
    candidateName: 'Maya Lin',
    candidateEmail: 'maya.lin@cognitiveintelligence.ai',
    jobId: 'job-104',
    jobTitle: 'Senior AI / ML Research Engineer',
    stage: 'NEW',
    appliedDate: '2026-03-16T12:00:00Z',
    source: 'Direct Sourcing',
    recruiterId: 'usr-3',
    recruiterName: 'Elena Rostova',
    rating: 4.5,
  },
  {
    id: 'app-505',
    candidateId: 'cand-5',
    candidateName: 'Rohan Mehta',
    candidateEmail: 'rohan.mehta@fintechstack.org',
    jobId: 'job-101',
    jobTitle: 'Senior Full Stack Engineer',
    stage: 'SCREENING',
    appliedDate: '2026-03-14T09:12:00Z',
    source: 'LinkedIn',
    recruiterId: 'usr-3',
    recruiterName: 'Elena Rostova',
    rating: 4.2,
  },
  {
    id: 'app-506',
    candidateId: 'cand-6',
    candidateName: 'Chloe Tremblay',
    candidateEmail: 'chloe.tremblay@enterpriseops.co',
    jobId: 'job-105',
    jobTitle: 'Customer Success & Onboarding Lead',
    stage: 'HIRED',
    appliedDate: '2026-01-20T10:00:00Z',
    source: 'Referral',
    recruiterId: 'usr-2',
    recruiterName: 'Marcus Vance',
    rating: 4.9,
  },
];

export const initialInterviews = [
  {
    id: 'int-701',
    candidateId: 'cand-1',
    candidateName: 'Alexander Wright',
    jobId: 'job-101',
    jobTitle: 'Senior Full Stack Engineer',
    interviewerId: 'usr-4',
    interviewerName: 'David Chen (VP of Engineering)',
    date: '2026-03-22',
    time: '14:00',
    timeZone: 'PST (UTC-8)',
    type: 'Technical',
    meetingLink: 'https://meet.google.com/xyz-hb-tech',
    status: 'SCHEDULED',
    notes: 'Focus on distributed caching, system design, and database deadlock avoidance.',
    feedback: null,
  },
  {
    id: 'int-702',
    candidateId: 'cand-3',
    candidateName: 'Julian Vance',
    jobId: 'job-103',
    jobTitle: 'Senior Product Designer',
    interviewerId: 'usr-1',
    interviewerName: 'Sarah Connor (Head of Talent Acquisition)',
    date: '2026-03-05',
    time: '15:30',
    timeZone: 'EST (UTC-5)',
    type: 'Final',
    meetingLink: 'https://meet.google.com/abc-hb-final',
    status: 'COMPLETED',
    notes: 'Executive alignment and cultural fit interview.',
    feedback: {
      rating: 5,
      recommendation: 'STRONG_YES',
      strengths: 'Remarkable design systems expertise, exceptional communicator, passionate about accessibility.',
      concerns: 'None identified.',
      privateNotes: 'Approved for top compensation tier.',
      submittedAt: '2026-03-05T17:00:00Z',
    },
  },
];

export const initialNotifications = [
  {
    id: 'notif-1',
    title: 'New Candidate Applied',
    message: 'Alexander Wright applied for Senior Full Stack Engineer.',
    type: 'candidate',
    isRead: false,
    createdAt: '2026-03-14T10:30:00Z',
    link: '/candidates/cand-1',
  },
  {
    id: 'notif-2',
    title: 'Publication Request Pending Review',
    message: 'Job "Lead DevOps & Cloud Architect" is pending Admin Publication Queue review.',
    type: 'job',
    isRead: false,
    createdAt: '2026-03-10T09:35:00Z',
    link: '/jobs/job-102',
  },
  {
    id: 'notif-3',
    title: 'Interview Scheduled',
    message: 'Technical round scheduled with Alexander Wright on March 22, 2:00 PM PST.',
    type: 'interview',
    isRead: true,
    createdAt: '2026-03-06T10:05:00Z',
    link: '/interviews/int-701',
  },
  {
    id: 'notif-4',
    title: 'Candidate Offer Extended',
    message: 'Offer letter extended to Julian Vance for Senior Product Designer.',
    type: 'offer',
    isRead: true,
    createdAt: '2026-03-08T16:05:00Z',
    link: '/applications/app-503',
  },
];

export const initialAdminPublications = [
  {
    id: 'pub-801',
    jobId: 'job-102',
    jobTitle: 'Lead DevOps & Cloud Architect',
    organizationId: 'org-1',
    organizationName: 'Apex Global Tech',
    requestedBy: 'Elena Rostova',
    requestedDate: '2026-03-10T09:30:00Z',
    targetPlatform: 'MANUAL',
    status: 'PENDING',
    internalNotes: 'Awaiting recruiter client confirmation on remote budget caps before pushing to manual board.',
  },
  {
    id: 'pub-802',
    jobId: 'job-101',
    jobTitle: 'Senior Full Stack Engineer',
    organizationId: 'org-1',
    organizationName: 'Apex Global Tech',
    requestedBy: 'Elena Rostova',
    requestedDate: '2026-03-01T11:00:00Z',
    targetPlatform: 'MANUAL',
    status: 'PUBLISHED',
    publishedDate: '2026-03-02T14:30:00Z',
    internalNotes: 'Verified job specifications, published to active portal.',
  },
];

export const initialAuditLogs = [
  {
    id: 'audit-1',
    actor: 'Elena Rostova',
    role: 'RECRUITER',
    action: 'JOB_CREATED',
    entity: 'Job',
    entityId: 'job-102',
    entityName: 'Lead DevOps & Cloud Architect',
    date: '2026-03-10T09:15:00Z',
    organization: 'Apex Global Tech',
    ipAddress: '198.51.100.42',
  },
  {
    id: 'audit-2',
    actor: 'Elena Rostova',
    role: 'RECRUITER',
    action: 'PUBLICATION_REQUESTED',
    entity: 'JobDistribution',
    entityId: 'pub-801',
    entityName: 'Lead DevOps & Cloud Architect',
    date: '2026-03-10T09:30:00Z',
    organization: 'Apex Global Tech',
    ipAddress: '198.51.100.42',
  },
  {
    id: 'audit-3',
    actor: 'Sarah Connor',
    role: 'OWNER',
    action: 'OFFER_EXTENDED',
    entity: 'Application',
    entityId: 'app-503',
    entityName: 'Julian Vance (Design Systems)',
    date: '2026-03-08T16:00:00Z',
    organization: 'Apex Global Tech',
    ipAddress: '198.51.100.18',
  },
  {
    id: 'audit-4',
    actor: 'Alex Mercer',
    role: 'SUPER_ADMIN',
    action: 'ADMIN_JOB_PUBLISHED',
    entity: 'JobPublication',
    entityId: 'pub-802',
    entityName: 'Senior Full Stack Engineer',
    date: '2026-03-02T14:30:00Z',
    organization: 'HirebridgeHR Operations',
    ipAddress: '203.0.113.99',
  },
];

// ---- CANDIDATE DATA MODELS ----
export const initialCandidateProfile = {
  id: 'cand-prof-1',
  userId: 'usr-cand-1',
  firstName: 'Alex',
  lastName: 'Rivera',
  email: 'alex.candidate@example.com',
  phone: '+1 (555) 234-5678',
  location: 'San Francisco, CA',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  headline: 'Senior Full Stack & React Native Developer | 5+ Yrs Exp',
  currentTitle: 'Senior Full Stack Engineer',
  currentCompany: 'TechNova Solutions',
  experienceYears: 5,
  skills: [
    'React.js',
    'React Native',
    'TypeScript',
    'Node.js',
    'PostgreSQL',
    'Tailwind CSS',
    'Docker',
    'AWS',
    'GraphQL',
  ],
  education: [
    {
      id: 'edu-1',
      degree: 'B.S. in Computer Science',
      university: 'University of California, Berkeley',
      startYear: '2016',
      endYear: '2020',
    },
  ],
  workExperience: [
    {
      id: 'exp-1',
      company: 'TechNova Solutions',
      position: 'Senior Full Stack Engineer',
      startDate: '2022-03',
      endDate: 'Present',
      description: 'Architected high-throughput React frontends and Node.js microservices serving 150,000+ daily active users.',
    },
    {
      id: 'exp-2',
      company: 'Vanguard Mobile Studio',
      position: 'Frontend & Mobile Engineer',
      startDate: '2020-06',
      endDate: '2022-02',
      description: 'Built cross-platform React Native mobile applications and integrated automated CI/CD pipelines.',
    },
  ],
  projects: [
    {
      id: 'proj-1',
      name: 'CloudScale ATS Platform',
      description: 'Open-source distributed job tracking pipeline with real-time webhooks and liquid glass UI.',
      technologies: ['React', 'Node.js', 'Redis', 'Tailwind'],
      url: 'https://github.com/alexrivera/cloudscale-ats',
    },
    {
      id: 'proj-2',
      name: 'PulseFlow Design System',
      description: 'Component library built with modern accessibility standards and Figma token synchronizer.',
      technologies: ['TypeScript', 'Tailwind CSS', 'Storybook'],
      url: 'https://pulseflow.dev',
    },
  ],
  resumeUrl: '/resumes/alex-rivera-resume-2026.pdf',
  resumeFileName: 'Alex_Rivera_FullStack_Resume.pdf',
  resumeFileSize: '1.4 MB',
  resumeUploadedAt: '2026-03-01T10:00:00Z',
  linkedinUrl: 'https://linkedin.com/in/alex-rivera-dev',
  githubUrl: 'https://github.com/alexrivera-dev',
  portfolioUrl: 'https://alexrivera.dev',
  profileCompletion: 92,
  createdAt: '2025-02-10T12:00:00Z',
  updatedAt: '2026-03-10T09:00:00Z',
};

export const initialSavedJobs = [
  'job-101', // Senior Full Stack Engineer
  'job-103', // Senior Product Designer
  'job-104', // Machine Learning & LLM Engineer
];

export const initialCandidateNotifications = [
  {
    id: 'c-notif-1',
    candidateId: 'usr-cand-1',
    title: 'Shortlisted for Interview',
    message: 'Elena Rostova moved your application for Senior Full Stack Engineer at Apex Global Tech to Shortlisted stage.',
    type: 'SHORTLISTED',
    jobId: 'job-101',
    isRead: false,
    createdAt: '2026-03-18T14:30:00Z',
    link: '/candidate/applications',
  },
  {
    id: 'c-notif-2',
    candidateId: 'usr-cand-1',
    title: 'Technical Interview Scheduled',
    message: 'Your Technical Assessment round with David Chen is confirmed for March 22 at 2:00 PM EST.',
    type: 'INTERVIEW',
    jobId: 'job-101',
    isRead: false,
    createdAt: '2026-03-17T11:00:00Z',
    link: '/candidate/applications',
  },
  {
    id: 'c-notif-3',
    candidateId: 'usr-cand-1',
    title: 'Application Submitted',
    message: 'Your application for Lead DevOps & Cloud Architect at Apex Global Tech has been received.',
    type: 'APPLIED',
    jobId: 'job-102',
    isRead: true,
    createdAt: '2026-03-15T09:15:00Z',
    link: '/candidate/applications',
  },
];

